title: "Robin Sch\"afer"
description: "Computational Physicist"
baseurl: ""
url: "https://robin-schaefer.github.io"
theme: minima
email: "rschaefe@bu.edu"


markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

